/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package src;

import static src.PruebaAdmonConsolas.ac;

/**
 *
 * @author Geraf
 */
public class FrmConsGral extends javax.swing.JDialog {

    /**
     * Creates new form FrmConsGral
     */
    public FrmConsGral(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsolas = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA GENERAL CONSOLAS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtConsolas.setColumns(20);
        txtConsolas.setRows(5);
        txtConsolas.setEnabled(false);
        jScrollPane1.setViewportView(txtConsolas);

        btnRegresar.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int clave, generacion;
        String nombre, tipo;
        float precio;
        Consola consolasT[];
        
        consolasT = ac.consultaGeneral();
        txtConsolas.setText("");
        for (int x = 0; x < consolasT.length; x++) {
            clave = consolasT[x].getClave();
            generacion = consolasT[x].getGeneracion();
            nombre = consolasT[x].getNombre();
            if (consolasT[x] instanceof ConsolaDeSobremesa) {
                tipo = "Consola de Sobremesa";
                precio = ((ConsolaDeSobremesa)consolasT[x]).calcularPrecioFinal();
            } else {
                tipo = "Consola Portatil";
                precio = ((ConsolaPortatil)consolasT[x]).calcularPrecioFinal();
            }
            txtConsolas.setText(txtConsolas.getText() + 
                    "Clave: " + String.valueOf(clave) + "\n" +
                    "Tipo: " + tipo + "\n" +
                    "Nombre: " + nombre + "\n" +
                    "Generacion: " + generacion + "\n" +
                    "Precio: " + String.valueOf(precio) + "\n" +
                    "---------------------------------------------\n\n");
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtConsolas;
    // End of variables declaration//GEN-END:variables
}
