/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package src;

import javax.swing.JOptionPane;
import static src.PruebaAdmonConsolas.ac;

/**
 *
 * @author Geraf
 */
public class FrmModPortatil extends javax.swing.JDialog {

    int celda, clave;
    /**
     * Creates new form FrmModPortatil
     */
    public FrmModPortatil(java.awt.Frame parent, boolean modal, int clave, int celda) {
        super(parent, modal);
        this.clave = clave;
        this.celda = celda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpPortatiles = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtGeneracion = new javax.swing.JTextField();
        rbtNombre = new javax.swing.JRadioButton();
        txtPrecio = new javax.swing.JTextField();
        rbtGeneracion = new javax.swing.JRadioButton();
        txtBateria = new javax.swing.JTextField();
        rbtPrecio = new javax.swing.JRadioButton();
        txtPantalla = new javax.swing.JTextField();
        rbtPantalla = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();
        btnElegir = new javax.swing.JButton();
        rbtBateria = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFICACION DE UNA CONSOLA PORTATIL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setText("¿Que desa modificar?     clave de la consola:");

        txtGeneracion.setEnabled(false);

        grpPortatiles.add(rbtNombre);
        rbtNombre.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtNombre.setSelected(true);
        rbtNombre.setText("Nombre:");

        txtPrecio.setEnabled(false);

        grpPortatiles.add(rbtGeneracion);
        rbtGeneracion.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtGeneracion.setText("Generacion:");

        txtBateria.setEnabled(false);

        grpPortatiles.add(rbtPrecio);
        rbtPrecio.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtPrecio.setText("Precio:");

        txtPantalla.setEnabled(false);

        grpPortatiles.add(rbtPantalla);
        rbtPantalla.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtPantalla.setText("Tamaño de la pantalla:");

        btnModificar.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnElegir.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnElegir.setText("Elegir");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        grpPortatiles.add(rbtBateria);
        rbtBateria.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtBateria.setText("Duracion max. de la bateria:");

        jLabel1.setText("pulgadas");

        txtClave.setEnabled(false);

        txtNombre.setEnabled(false);

        jLabel4.setText("PESOS");

        jLabel3.setText("HRS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(rbtNombre)
                                .addComponent(rbtPrecio))
                            .addComponent(rbtBateria)
                            .addComponent(rbtPantalla)
                            .addComponent(rbtGeneracion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtGeneracion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(rbtPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(rbtPantalla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtBateria)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnElegir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Consola c = new ConsolaPortatil(Float.parseFloat(txtPantalla.getText()), Integer.parseInt(txtBateria.getText()), clave,
            txtNombre.getText(), Integer.parseInt(txtGeneracion.getText()), Float.parseFloat(txtPrecio.getText()));
        ac.modificar(c, celda);
        JOptionPane.showConfirmDialog(this,
            "La cosola portatil fue modificada",
            "Modificacion exitosa",
            JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        if (rbtNombre.isSelected()) {
            txtNombre.setEnabled(true);
        } else if (rbtGeneracion.isSelected()) {
            txtGeneracion.setEnabled(true);
        } else if (rbtPrecio.isSelected()) {
            txtPrecio.setEnabled(true);
        } else if (rbtPantalla.isSelected()) {
            txtPantalla.setEnabled(true);
        } else {
            txtBateria.setEnabled(true);
        }
    }//GEN-LAST:event_btnElegirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Consola c = ac.getConsola(celda);
        txtClave.setText(String.valueOf(clave));
        String nombre = c.getNombre();
        int generacion = c.getGeneracion();
        float tamPantalla = ((ConsolaPortatil)c).getTamPantalla();
        int bateria = ((ConsolaPortatil)c).getBateria();
        float precio = ((ConsolaPortatil)c).calcularPrecioFinal();
        
        txtNombre.setText(nombre);
        txtGeneracion.setText(String.valueOf(generacion));
        txtPantalla.setText(String.valueOf(tamPantalla));
        txtBateria.setText(String.valueOf(bateria));
        txtPrecio.setText(String.valueOf(precio));
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup grpPortatiles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtBateria;
    private javax.swing.JRadioButton rbtGeneracion;
    private javax.swing.JRadioButton rbtNombre;
    private javax.swing.JRadioButton rbtPantalla;
    private javax.swing.JRadioButton rbtPrecio;
    private javax.swing.JTextField txtBateria;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtGeneracion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
