/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package src;

import javax.swing.JOptionPane;
import static src.PruebaAdmonConsolas.ac;

/**
 *
 * @author Geraf
 */
public class FrmModSobremesa extends javax.swing.JDialog {

    int clave, celda;
    /**
     * Creates new form FrmModSobremesa
     */
    public FrmModSobremesa(java.awt.Frame parent, boolean modal, int clave, int celda) {
        super(parent, modal);
        this.clave = clave;
        this.celda = celda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpModificar = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rbtNombre = new javax.swing.JRadioButton();
        rbtGeneracion = new javax.swing.JRadioButton();
        rbtPrecio = new javax.swing.JRadioButton();
        rbtDiscoDuro = new javax.swing.JRadioButton();
        rbtVideo = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        txtGeneracion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtVideo = new javax.swing.JTextField();
        txtDiscoDuro = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnElegir = new javax.swing.JButton();
        txtClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFICACION DE UNA CONSOLA DE SOBREMESA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setText("¿Que desa modificar?     clave de la consola:");

        grpModificar.add(rbtNombre);
        rbtNombre.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtNombre.setSelected(true);
        rbtNombre.setText("Nombre:");

        grpModificar.add(rbtGeneracion);
        rbtGeneracion.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtGeneracion.setText("Generacion:");

        grpModificar.add(rbtPrecio);
        rbtPrecio.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtPrecio.setText("Precio:");

        grpModificar.add(rbtDiscoDuro);
        rbtDiscoDuro.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtDiscoDuro.setText("Capacidad del disco duro:");

        grpModificar.add(rbtVideo);
        rbtVideo.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        rbtVideo.setText("Entrada de video");

        txtNombre.setEnabled(false);

        txtGeneracion.setEnabled(false);

        txtPrecio.setEnabled(false);

        txtVideo.setEnabled(false);

        txtDiscoDuro.setEnabled(false);

        btnModificar.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("GB");

        jLabel4.setText("PESOS");

        btnElegir.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnElegir.setText("Elegir");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        txtClave.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(rbtNombre)
                                .addComponent(rbtPrecio))
                            .addComponent(rbtVideo)
                            .addComponent(rbtDiscoDuro)
                            .addComponent(rbtGeneracion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(txtVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtGeneracion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(rbtPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(rbtDiscoDuro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtVideo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnElegir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        if (rbtNombre.isSelected()) {
            txtNombre.setEnabled(true);
        } else if (rbtGeneracion.isSelected()) {
            txtGeneracion.setEnabled(true);
        } else if (rbtPrecio.isSelected()) {
            txtPrecio.setEnabled(true);
        } else if (rbtDiscoDuro.isSelected()) {
            txtDiscoDuro.setEnabled(true);
        } else {
            txtVideo.setEnabled(true);
        }
    }//GEN-LAST:event_btnElegirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Consola c = new ConsolaDeSobremesa(Integer.parseInt(txtDiscoDuro.getText()), txtVideo.getText(), clave,
                txtNombre.getText(), Integer.parseInt(txtGeneracion.getText()), Float.parseFloat(txtPrecio.getText()));
        ac.modificar(c, celda);
        JOptionPane.showConfirmDialog(this,
                "La cosola de sobremesa fue modificada",
                "Modificacion exitosa",
                JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Consola c = ac.getConsola(celda);
        txtClave.setText(String.valueOf(clave));
        String nombre = c.getNombre();
        int generacion = c.getGeneracion();
        int discoDuro = ((ConsolaDeSobremesa)c).getDiscoDuro();
        String salidaDeVideo = ((ConsolaDeSobremesa)c).getSalidaDeVideo();
        float precio = ((ConsolaDeSobremesa)c).calcularPrecioFinal();
        
        txtNombre.setText(nombre);
        txtGeneracion.setText(String.valueOf(generacion));
        txtDiscoDuro.setText(String.valueOf(discoDuro));
        txtVideo.setText(salidaDeVideo);
        txtPrecio.setText(String.valueOf(precio));
        
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup grpModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtDiscoDuro;
    private javax.swing.JRadioButton rbtGeneracion;
    private javax.swing.JRadioButton rbtNombre;
    private javax.swing.JRadioButton rbtPrecio;
    private javax.swing.JRadioButton rbtVideo;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDiscoDuro;
    private javax.swing.JTextField txtGeneracion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtVideo;
    // End of variables declaration//GEN-END:variables
}
